---
- name: Install mailman via apt
  apt: pkg={{ item }} state=present
  with_items:
    - mailman
  tags:
    - mailman

- name: install mailman config
  template: src=mm_cfg.py.j2 dest=/etc/mailman/mm_cfg.py
  tags:
    - mailman
  notify:
    - restart mailman

- name: check for existing lists
  command: "list_lists -b"
  register: mailman_existing_lists
  tags:
    - mailman

- name: create site list
  command: "newlist -q {{ mailman_site_list }} {{ mailman_site_list_email }} {{ mailman_site_list_password }}"
  when: mailman_site_list not in mailman_existing_lists.stdout_lines
  tags:
    - mailman

- name: create mailing lists
  shell: yes | newlist
               "--urlhost={{ item.initial_settings.urlhost | default(mailman_default_url_host) }}"
               "--emailhost={{ item.initial_settings.emailhost | default(mailman_default_email_host) }}"
               "{{ item.name }}"
               "{{ item.initial_settings.admin_email }}"
               "{{ item.initial_settings.admin_password }}"
  with_items: "{{ mailman_mailing_lists }}"
  when: item.name not in mailman_existing_lists.stdout_lines
  tags:
    - mailman

- name: create tmpfiles for new list configs
  command: mktemp
  with_items: "{{ mailman_mailing_lists }}"
  when: item.name not in mailman_existing_lists.stdout_lines
  register: mailman_config_tmpfiles
  tags:
    - mailman

- name: upload new lists configs
  template: src=list_config.py.j2 dest="{{ item.stdout }}"
  with_items: "{{ mailman_config_tmpfiles.results }}"
  when: item.changed
  tags:
    - mailman

- name: configure mailing lists
  command: config_list --inputfile "{{ item.stdout }}" "{{ item.item.name }}"
  with_items: mailman_config_tmpfiles.results
  when: item.changed
  tags:
    - mailman

- name: delete tmpfiles
  file: path="{{ item.stdout }}" state=absent
  with_items: mailman_config_tmpfiles.results
  when: item.changed
  tags:
    - mailman

- name: create mailing list aliases
  template: src=list-aliases.j2 dest="/etc/postfix/aliases.d/{{ item.name }}.aliases"
  with_items: mailman_mailing_lists
  notify:
    - update include alias file
  tags:
    - postfix
    - mailman

- name: create www document root
  file: path=/var/www/lists state=directory
  tags:
    - mailman

- name: install lighttpd config for mailman
  template: src=lighttpd.conf.j2 dest=/etc/lighttpd/conf-enabled/mailman.conf
  tags:
    - mailman
    - lighttpd
  notify:
    - restart lighttpd
